-- begin SAMPLE_TERMINAL
alter table SAMPLE_TERMINAL add constraint FK_SAMPLE_TERMINAL_AIRPORT foreign key (AIRPORT_ID) references SAMPLE_AIRPORT(ID)^
create index IDX_SAMPLE_TERMINAL_AIRPORT on SAMPLE_TERMINAL (AIRPORT_ID)^
-- end SAMPLE_TERMINAL
-- begin SAMPLE_MEETING_POINT
alter table SAMPLE_MEETING_POINT add constraint FK_SAMPLE_MEETING_POINT_TERMINAL foreign key (TERMINAL_ID) references SAMPLE_TERMINAL(ID)^
create index IDX_SAMPLE_MEETING_POINT_TERMINAL on SAMPLE_MEETING_POINT (TERMINAL_ID)^
-- end SAMPLE_MEETING_POINT
-- begin SAMPLE_NOTE
alter table SAMPLE_NOTE add constraint FK_SAMPLE_NOTE_MEETING_POINT foreign key (MEETING_POINT_ID) references SAMPLE_MEETING_POINT(ID)^
create index IDX_SAMPLE_NOTE_MEETING_POINT on SAMPLE_NOTE (MEETING_POINT_ID)^
-- end SAMPLE_NOTE
